src/SmartAdmin.WebUI/Controllers/EnderecosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using AutoMapper;
using Cooperchip.ITDeveloper.Farmacia.Domain.Entities;
using Cooperchip.ITDeveloper.Farmacia.Domain.Interfaces;
using Cooperchip.ITDeveloper.Farmacia.Domain.Notificacoes;
using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Cooperchip.ITDeveloper.Mvc.Controllers
{
    public class EnderecosController : BaseController
    {

        private readonly IEnderecoRepository _enderecoRepository;
        private readonly IFornecedorRepository _fornecedorRepository;
        private readonly IEnderecoService _enderecoService;
        private readonly IMapper _mapper;

        public EnderecosController(INotificador notificador, IEnderecoRepository enderecoRepository,
            IFornecedorRepository fornecedorRepository, IEnderecoService enderecoService, IMapper mapper) : base(notificador)
        {
            _enderecoRepository = enderecoRepository;
            _fornecedorRepository = fornecedorRepository;
            _enderecoService = enderecoService;
            _mapper = mapper;

        }

        [Route("lista-de-enderecos")]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<EnderecoViewModel>>(await _enderecoRepository.ObterEnderecosFornecedores()));
        }

        [Route("dados-do-endereco/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {

            var enderecoViewModel = _mapper.Map<EnderecoViewModel>(await _enderecoRepository.ObterEnderecoFornecedor(id));
            enderecoViewModel.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

            if (enderecoViewModel == null)
            {
                return NotFound();
            }

            return View(enderecoViewModel);
        }


        #region: Usando PopularFornecedores
        [Route("novo-endereco")]
        public async Task<IActionResult> Create()
        {
            var enderecoViewModel = await PopularFornecedores(new EnderecoViewModel());

            return View(enderecoViewModel);
        }



        [Route("novo-endereco")]
        [HttpPost]
        public async Task<IActionResult> Create(EnderecoViewModel enderecoViewModel)
        {
            enderecoViewModel = await PopularFornecedores(enderecoViewModel);

            if (!ModelState.IsValid) return View(enderecoViewModel);

            await _enderecoService.Adicionar(_mapper.Map<Endereco>(enderecoViewModel));

            if (!OperacaoValida()) return View(enderecoViewModel);

            return RedirectToAction(nameof(Index), "Fornecedores");
        }


        /// <summary>
        /// Usado para popular a lista de Fornecedores para o DropDown
        /// de onde pode-se escolher de quel Fornecedor pertence o Endereco!
        /// </summary>
        /// <param name="enderecoViewModel"></param>
        /// <returns></returns>
        private async Task<EnderecoViewModel> PopularFornecedores(EnderecoViewModel enderecoViewModel)
        {
            enderecoViewModel.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());
            return enderecoViewModel;
        }
        #endregion



        [Route("editar-endereco/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var enderecoViewModel = _mapper.Map<EnderecoViewModel>(await _enderecoRepository.ObterEnderecoFornecedor(id));

            if (enderecoViewModel == null)
            {
                return NotFound();
            }

            return View(enderecoViewModel);
        }

        [Route("editar-endereco/{id:guid}")]
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, EnderecoViewModel enderecoViewModel)
        {
            if (id != enderecoViewModel.Id) return NotFound();

            var enderecoAtualizacao = _mapper.Map<EnderecoViewModel>(await _enderecoRepository.ObterEnderecoFornecedor(id));

            enderecoAtualizacao.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

            enderecoViewModel.Fornecedor = enderecoAtualizacao.Fornecedor;

            if (!ModelState.IsValid) return View(enderecoViewModel);


            enderecoAtualizacao.Cep = enderecoViewModel.Cep;
            enderecoAtualizacao.Estado = enderecoViewModel.Estado;
            enderecoAtualizacao.Bairro = enderecoViewModel.Bairro;
            enderecoAtualizacao.Logradouro = enderecoViewModel.Logradouro;
            enderecoAtualizacao.Cidade = enderecoViewModel.Cidade;
            enderecoAtualizacao.Estado = enderecoViewModel.Estado;
            enderecoAtualizacao.Complemento = enderecoViewModel.Complemento;
            enderecoAtualizacao.Numero = enderecoViewModel.Numero;


            await _enderecoService.Atualizar(_mapper.Map<Endereco>(enderecoAtualizacao));

            if (!OperacaoValida()) return View(enderecoViewModel);

            return RedirectToAction("Index");
        }

        [Route("excluir-endereco/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var endereco = _mapper.Map<EnderecoViewModel>(await _enderecoRepository.ObterEnderecoFornecedor(id));
            endereco.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);
        }


        [Route("excluir-endereco/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var enderecoViewModel = _mapper.Map<EnderecoViewModel>(await _enderecoRepository.ObterEnderecoFornecedor(id));

            enderecoViewModel.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

            if (enderecoViewModel == null)
            {
                return NotFound();
            }

            await _enderecoService.Remover(id);

            if (!OperacaoValida()) return View(enderecoViewModel);

            TempData["Sucesso"] = "Endereco excluido com sucesso!";

            return RedirectToAction("Index");
        }


    }
}

src/SmartAdmin.WebUI/Views/Enderecos/Create.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model EnderecoViewModel

@{
    ViewData["Title"] = "Novo Endereco";
    ViewData["PageName"] = "adicionar_produto";
    ViewData["Heading"] = "<i class='subheader-icon fal fa-edit'></i>  Novo Endereco";
    ViewData["Category1"] = "Endereco";
    ViewData["PageDescription"] = "Processo de inclus&atilde;o de Endereco";
}
<div class="row">
    <div class="col-xl-12 col-md-12 col-sm-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <div class="panel-toolbar">
                    <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                    <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <div class="col-md-12">

                        <form enctype="multipart/form-data" asp-controller="Enderecos" asp-action="Create">

                            <vc:Summary></vc:Summary>

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="FornecedorId" class="control-label"></label>
                                <select asp-for="FornecedorId" class="form-control" asp-items="@(new SelectList(Model.Fornecedores, "Id", "Nome"))">
                                    <option></option>
                                </select>

                                <span asp-validation-for="FornecedorId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Logradouro" class="control-label"></label>
                                <input asp-for="Logradouro" class="form-control" />
                                <span asp-validation-for="Logradouro" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Numero" class="control-label"></label>
                                <input asp-for="Numero" class="form-control" />
                                <span asp-validation-for="Numero" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="Complemento" class="control-label"></label>
                                <textarea cols="40" rows="5" asp-for="Complemento" class="form-control"></textarea>
                                <span asp-validation-for="Complemento" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Cep" class="control-label"></label>
                                <input asp-for="Cep" class="form-control" />
                                <span asp-validation-for="Cep" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Bairro" class="control-label"></label>
                                <input asp-for="Bairro" class="form-control" />
                                <span asp-validation-for="Bairro" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Cidade" class="control-label"></label>
                                <input asp-for="Cidade" class="form-control" />
                                <span asp-validation-for="Cidade" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Estado" class="control-label"></label>
                                <input asp-for="Estado" class="form-control" />
                                <span asp-validation-for="Estado" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <button type="submit" value="Cadastrar" class="btn btn-outline-primary" >Cadastrar</button>
                                <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }


    <script>
        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImagemUpload").attr("data-val", "true");
        $("#ImagemUpload").attr("data-val-required", "Preencha o campo Imagem");
    </script>
}

src/SmartAdmin.WebUI/Views/Enderecos/Delete.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model EnderecoViewModel

@{
    ViewData["Title"] = "Excluir " + Model.Logradouro;
}

@{
    ViewData["Title"] = $"Excluir Endereco - {Model.Logradouro}";
    ViewData["PageName"] = "excluir-produto";
    ViewData["Category1"] = "Endereco";
    ViewData["Heading"] = "<i class='subheader-icon fal fa-table'></i> Excluir Endereco: " + Model.Logradouro;
}

@section HeadBlock {
    <link rel="stylesheet" media="screen, print" href="~/css/page-invoice.css">
}
<div class="container">
    <div data-size="A4">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="fw-400 display-4 fw-350 color-primary-600 keep-print-font pt-4 l-h-n m-0">
                    Confirma a exclusão de: @Model.Logradouro
                </h3>
                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 d-flex">
                <div class="table-responsive">
                    <div class="col-md-6">
                        <dl>
                            <dt>
                                @Html.DisplayNameFor(model => model.FornecedorId)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Fornecedor.Nome)
                            </dd>

                            <dt>@Html.DisplayNameFor(model => model.Logradouro)</dt>
                            <dd>@Html.DisplayFor(model => model.Logradouro)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Numero)</dt>
                            <dd>@Html.DisplayFor(model => model.Numero)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Complemento)</dt>
                            <dd>@Html.DisplayFor(model => model.Complemento)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Cep)</dt>
                            <dd>@Html.DisplayFor(model => model.Cep)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Bairro)</dt>
                            <dd>@Html.DisplayFor(model => model.Bairro)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Cidade)</dt>
                            <dd>@Html.DisplayFor(model => model.Cidade)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Estado)</dt>
                            <dd>@Html.DisplayFor(model => model.Estado)</dd>

                        </dl>

                        <div>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <button type="submit" value="Excluir" class="btn btn-outline-danger">Excluir</button>
                                <a class="btn btn-outline-info" href="javascript:window.history.back();">Voltar</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/SmartAdmin.WebUI/Views/Enderecos/Details.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model EnderecoViewModel

<!-- INVOICE TRIAGEM  -->
@{
    ViewData["Title"] = $"Detalhe do Endereco - {Model.Logradouro}";
    ViewData["PageName"] = "detalhe-de-produto";
    ViewData["Category1"] = "Endereco";
    ViewData["Heading"] = "<i class='subheader-icon fal fa-table'></i> Detalhes do Endereco: " + Model.Logradouro;
}

@section HeadBlock {
    <link rel="stylesheet" media="screen, print" href="~/css/page-invoice.css">
}
<div class="container">
    <div data-size="A4">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="fw-400 display-4 fw-350 color-primary-600 keep-print-font pt-4 l-h-n m-0">
                    @Model.Logradouro
                </h3>
                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 d-flex">
                <div class="table-responsive">

                    <div class="col-md-6">
                        <dl>
                            <dt>
                                @Html.DisplayNameFor(model => model.FornecedorId)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Fornecedor.Nome)
                            </dd>

                            <dt>@Html.DisplayNameFor(model => model.Logradouro)</dt>
                            <dd>@Html.DisplayFor(model => model.Logradouro)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Numero)</dt>
                            <dd>@Html.DisplayFor(model => model.Numero)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Complemento)</dt>
                            <dd>@Html.DisplayFor(model => model.Complemento)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Cep)</dt>
                            <dd>@Html.DisplayFor(model => model.Cep)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Bairro)</dt>
                            <dd>@Html.DisplayFor(model => model.Bairro)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Cidade)</dt>
                            <dd>@Html.DisplayFor(model => model.Cidade)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Estado)</dt>
                            <dd>@Html.DisplayFor(model => model.Estado)</dd>

                        </dl>

                        <div>
                            <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
                            <a class="btn btn-outline-secondary" href="javascript:window.history.back();">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/SmartAdmin.WebUI/Views/Enderecos/Edit.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model EnderecoViewModel

<!-- INVOICE TRIAGEM  -->
@{
    ViewData["Title"] = $"Editar Endereco - {Model.Logradouro}";
    ViewData["PageName"] = "editar-produto";
    ViewData["Category1"] = "Endereco";
    ViewData["Heading"] = "<i class='subheader-icon fal fa-table'></i> Editar Endereco: " + Model.Logradouro;
}

@section HeadBlock {
    <link rel="stylesheet" media="screen, print" href="~/css/datagrid/datatables/datatables.bundle.css">
    <link rel="stylesheet" media="screen, print" href="~/css/fa-solid.css">
}

<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <div class="panel-toolbar">
                    <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                    <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">

                    <div class="panel panel-body">

                        <div class="row">
                            <div class="col-md-10">
                                <form enctype="multipart/form-data" asp-action="Edit">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                                    <input type="hidden" asp-for="Id" />

                                    <div class="form-group">
                                        <label asp-for="FornecedorId" class="control-label"></label><br />
                                        <label><b>@Model.Fornecedor.Nome</b></label>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="Logradouro" class="control-label"></label>
                                        <input asp-for="Logradouro" class="form-control" />
                                        <span asp-validation-for="Logradouro" class="text-danger"></span>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="Numero" class="control-label"></label>
                                        <input asp-for="Numero" class="form-control" />
                                        <span asp-validation-for="Numero" class="text-danger"></span>
                                    </div>


                                    <div class="form-group">
                                        <label asp-for="Complemento" class="control-label"></label>
                                        <textarea cols="40" rows="5" asp-for="Complemento" class="form-control"></textarea>
                                        <span asp-validation-for="Complemento" class="text-danger"></span>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="Cep" class="control-label"></label>
                                        <input asp-for="Cep" class="form-control" />
                                        <span asp-validation-for="Cep" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Bairro" class="control-label"></label>
                                        <input asp-for="Bairro" class="form-control" />
                                        <span asp-validation-for="Bairro" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Cidade" class="control-label"></label>
                                        <input asp-for="Cidade" class="form-control" />
                                        <span asp-validation-for="Cidade" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Estado" class="control-label"></label>
                                        <input asp-for="Estado" class="form-control" />
                                        <span asp-validation-for="Estado" class="text-danger"></span>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" value="Salvar" class="btn btn-outline-success">Salvar</button>
                                        <a class="btn btn-outline-secondary" href="javascript:window.history.back();">Voltar</a>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });
    </script>
}

src/SmartAdmin.WebUI/Views/Enderecos/Index.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model IEnumerable<EnderecoViewModel>


@{
    ViewData["Title"] = "Listagem de Enderecos";
    ViewData["PageName"] = "lista-de-enderecos";
    ViewData["Category1"] = "Enderecos";
    ViewData["Heading"] = "<i class='subheader-icon fal fa-table'></i> Listagem de Endereços: <span class='fw-300'>Módulo Endereço</span> <sup class='badge badge-primary fw-500'>ADDON</sup>";
    ViewData["PageDescription"] = "Exporte os dados para PDF, Excel e CSV sem qualquer complicação!";
}

@section HeadBlock {
    <link rel="stylesheet" media="screen, print" href="~/css/datagrid/datatables/datatables.bundle.css">
    <link rel="stylesheet" media="screen, print" href="~/css/fa-solid.css">
}


<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">

            <vc:summary></vc:summary>
@*            <partial name="PartialViews/_ListaEnderecosEmPartial" model="@Model.FornecedorEEnderecoViewModel" />*@
            <partial name="_ListaEnderecos" />

        </div>
    </div>
</div>



@section ScriptsBlock {
    <partial name="PartialViews/_ScriptDataTables" />
}

src/SmartAdmin.WebUI/Views/Enderecos/_ListaEnderecos.cshtml
@using Cooperchip.ITDeveloper.Mvc.ServiceApp.ViewModels;
@model IEnumerable<EnderecoViewModel>


@section HeadBlock {
    <link rel="stylesheet" media="screen, print" href="~/css/datagrid/datatables/datatables.bundle.css">
    <link rel="stylesheet" media="screen, print" href="~/css/fa-solid.css">
}


<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    <span supress-by-claim-name="Endereco" supress-by-claim-value="Adicionar">
                        <a class="btn btn-outline-info btn-sm" asp-controller="Enderecos" asp-action="Create">Novo Endereço</a>&nbsp;&nbsp;
                    </span>&nbsp;


                </h2>
                <div class="panel-toolbar">
                    <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                    <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">

                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100 dt-basic-srmartadmin">

                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Logradouro)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Numero)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Complemento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Cep)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Bairro)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Cidade)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Estado)
                                </th>


                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Logradouro)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Numero)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Complemento)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cep)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Bairro)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cidade)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Estado)
                                    </td>
                                    <td class="text-right">
                                        <a class="btn btn-outline-warning" asp-controller="Enderecos" asp-action="Details" asp-route-id="@item.Id"><spam class="fa fa-search"></spam> </a>
                                        <a disable-by-claim-name="Endereco" disable-by-claim-value="Editar" class="btn btn-outline-info" asp-controller="Enderecos" asp-action="Edit" asp-route-id="@item.Id"><spam class="fa fa-pencil-alt"></spam> </a>
                                        <a disable-by-claim-name="Endereco" disable-by-claim-value="Excluir" class="btn btn-outline-danger" asp-controller="Enderecos" asp-action="Delete" asp-route-id="@item.Id"><spam class="fa fa-trash"></spam> </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>


</div>



@section ScriptsBlock {
    <partial name="PartialViews/_ScriptDataTables" />
}